### PR TITLE
Remove :unneeded

### LINKED ISSUE #2: Brew: Warning: Calling bottle :unneeded is deprecated!
Got the following warning when updating brew.

```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the derailed/popeye tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/derailed/homebrew-popeye/Formula/popeye.rb:9
```

### PR DESCRIPTION
**Pull request by xaocon**
Simply removed the section as specified here https://github.com/Homebrew/discussions/discussions/2311?sort=top#discussioncomment-1507233

Closes #2

### CODE REVIEW

**Review by ivanblack19 — APPROVED** [review]

**Comment by xaocon** [comment]
Anything I can do to help this get merged?

**Comment by Moulick** [comment]
Closes https://github.com/derailed/popeye/issues/204

**Comment by Moulick** [comment]
@derailed would be much appreciated if this can be merged, this creates a lotta noise whenever any brew command it run :(

**Comment by xaocon** [comment]
Looks like this was handled in 0f7dbbb890fd04dc755f38d2e55fd9564c44d206. No need to keep this open.

**Pull request closed without merging**
